server:
  port: 9527

spring:
  application:
    name: springcloud-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    instance:
      instance-id: zuul9527.com
      prefer-ip-address: true
info:
  app.name: sylinx-springcloud
  company.name: blog.sylinx.com

zuul:
  routes:
    mydept.serviceId: springcloud-provider-dept
    mydept.path: /mydept/**
  ignored-services: "*"
  prefix: /sylinx